import type { WebSocket } from "ws";
import type { BotDecisionRecord, LoggedRoundResolution } from "../src/analytics";
import type { MatchAnalysis } from "../src/analysis";
import type { PersonaAggression, PublicActionEntry } from "../src/bot";
import type { Die, GameAction, GameRules, GameState } from "../src/engine";

export type RoomPlayer = { id: string; name: string; isBot: boolean; botPersona?: PersonaAggression; token?: string; socket?: WebSocket; disconnectedAt?: number };
export type RoomEvent = { type: "round-start" } | { type: "shuffle-dice" } | { type: "pause-game" } | { type: "resume-game" } | { type: "forfeit-game" };
export type Spectator = { socket: WebSocket; queuedPlayer?: RoomPlayer };
export type ConnectionContext = { connectionId: string; ipHash: string | null; ipVersion: "ipv4" | "ipv6" | "unknown"; forwardedForCount: number; userAgentHash: string | null; origin?: string; language?: string; protocol?: string; hashConfigured: boolean };
export type ConnectionEvent = ConnectionContext & { at: string; event: "room-created" | "player-joined" | "player-reconnected" | "player-queued" | "spectator-joined" | "disconnected"; role: "player" | "spectator"; playerId?: string };
export type LoggedAction = { at: string; round?: number; playerId?: string; nickname?: string; action: GameAction | RoomEvent; tableDice?: Die[]; rerolledDice?: Die[]; covered?: boolean };
export type RoundDeal = { round: number; dealtAt: string; paloFijo: boolean; starterId: string | null; hands: Array<{ playerId: string; nickname: string; dice: number[] }> };
export type TurnTiming = { round: number; playerId: string; nickname: string; controller: "human" | "bot"; startedAt: string; deadlineAt: string; finishedAt?: string; elapsedMs?: number; remainingMs?: number; outcome?: "bid" | "dudo" | "calzo" | "timeout" | "forfeit" | "interrupted" };
export type RoomRuleProposal = { rules: GameRules; proposedById: string; approvalPlayerIds: Set<string> };
export type PauseState = { pausedById: string; pausedAt: number; turnRemainingMs?: number; shuffleRemainingMs?: number; nextRoundRemainingMs?: number };

/** Authoritative in-memory room state. Private fields never cross the projection boundary. */
export type Room = {
  code: string;
  hostPlayerId: string;
  players: RoomPlayer[];
  spectators: Map<WebSocket, Spectator>;
  connectionEvents: ConnectionEvent[];
  rules: GameRules;
  pendingRules?: RoomRuleProposal;
  roundDeals: RoundDeal[];
  roundResolutions: LoggedRoundResolution[];
  turnTimings: TurnTiming[];
  activeTurn?: TurnTiming;
  game?: GameState;
  history: string[];
  botHistory: PublicActionEntry[];
  botDecisions: BotDecisionRecord[];
  analysis?: MatchAnalysis;
  announcement?: { text: string; playerId?: string };
  shuffleReadyPlayerIds?: Set<string>;
  nextRoundReadyPlayerIds?: Set<string>;
  nextRoundDeadlineAt?: number;
  shuffleDeadlineAt?: number;
  paused?: PauseState;
  actions: LoggedAction[];
  startedAt?: string;
  lastActivityAt: number;
  nextGameStarterId?: string;
  turnDeadlineAt?: number;
  turnTimer?: ReturnType<typeof setTimeout>;
  shuffleTimer?: ReturnType<typeof setTimeout>;
  nextRoundTimer?: ReturnType<typeof setTimeout>;
  offlineCoverTimer?: ReturnType<typeof setTimeout>;
  snapshotTimer?: ReturnType<typeof setTimeout>;
  snapshotPersisting?: boolean;
  snapshotQueued?: boolean;
  snapshotDeleteQueued?: boolean;
  expired?: boolean;
  lastSnapshotAt?: number;
  botShuffleTimers?: Array<ReturnType<typeof setTimeout>>;
  botNextRoundTimers?: Array<ReturnType<typeof setTimeout>>;
};
