export const BOT_NAMES = [
  "Khaleesi",
  "Calculator",
  "Berioska",
  "Miss Blanquita",
  "Pichulín",
  "Monkoky",
  "Matt Millan",
  "Gonchi",
  "El Gordo",
  "Asleigh Costley",
  "Min-chi Park",
  "Henry Sarria",
  "Fogey Baxter",
  "Poeta Dalmacia",
  "Balú Johnson",
  "McDonald Lewis",
  "Luciano Torres",
  "La Del Burro",
  "Tachi Cabrera",
] as const;
